(* let test pat expected = *)
(*   let instr = Pattern.compile pat in *)
(*   let instrs = Machine.run pat input in *)
(*   assert (instrs = expected) *)
(**)
(* let ()  = test Pattern.empty [Op.Empty] *)
